line-length = 100

[format]
quote-style = "single"
skip-magic-trailing-comma = false
exclude = [".venv/"]

[lint]
select = ["ALL"]
ignore = ["D", "TC001", "TC002"]
exclude = [".venv/"]

[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"
